package View;

import ConnectionFactory.Server;
import java.awt.Point;
import java.util.Random;

/**
 *
 * @author will
 */
public class CodePanel extends javax.swing.JFrame {

    public static String codeAuth = "";
    public static boolean cad;

    public CodePanel(Point l, boolean c) {
        this.cad = c;
        initComponents();
        setLocation(l);
        setLocation(getLocation().x - 25, getLocation().y + 75);
        randNumber();
        port.setText("PORT : " + BiometricServer.getPortAdress());
        ip.setText("IP : " + Server.getHostAdress());
    }

    public static boolean isCad() {
        return cad;
    }

    public CodePanel() {

    }

    private void randNumber() {
        Random random = new Random();
        code.setText(String.valueOf(String.format("%04d", random.nextInt(9999))));
        this.codeAuth = code.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        code = new javax.swing.JLabel();
        port = new javax.swing.JLabel();
        ip = new javax.swing.JLabel();

        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        code.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 48)); // NOI18N
        code.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        code.setText("2145");

        port.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        port.setText(" PORT : 0000 ");

        ip.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        ip.setText("IP : 000.000.0.000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(code, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(port)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(port)
                    .addComponent(ip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(code)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        setVisible(false);
    }//GEN-LAST:event_formWindowLostFocus

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel code;
    private javax.swing.JLabel ip;
    private javax.swing.JLabel port;
    // End of variables declaration//GEN-END:variables
}
